Beta with aiormq 4
mosquito/aio-pika pull request #381
Opened 2021-02-26 14:44 UTC by mosquito

2021-02-26 22:04 UTC, decaz requested changes

2021-04-16 18:10 UTC, mosquito commented on aio_pika/channel.py
> +        self._closed: bool = False
That's indicates the channel manually closed by user

2021-04-16 20:11 UTC, mosquito commented on aio_pika/message.py
> -@header_converter.register(bytes)
because bytes is the default now

2021-05-01 09:20 UTC, decaz requested changes

2021-05-01 09:20 UTC, decaz commented on aio_pika/queue.py
> +    def __channel(self) -> aiormq.Channel:
What do you think about naming it `_channel`?

2021-11-02 09:33 UTC, mosquito commented on setup.py
> +    install_requires=["aiormq~=5.1.0", "yarl"],
WIP

2021-12-31 06:11 UTC, julianfortune commented
Upgrading to this branch seems to have resolved an issue my team was having (similar to #288) and also allows setting the `timeout` parameter via URI query params; I know you are busy, so if you need any assistance with development or testing please let me know! Thank you for all of your work on this ❤️

2021-12-31 09:28 UTC, mosquito commented
@julianfortune Thank you for these kind words. Of course, I need help with testing, since there are a lot of changes and I tried to make the old tests pass, but there are still a lot of changes and testing will be required. If you find a bug, fell free to write comments in this review.

2022-01-24 23:00 UTC, closed without merging

2022-01-25 09:03 UTC, mosquito commented
Rebased and reworked in #436