Featire/wait reopen channel state
mosquito/aio-pika pull request #533
Opened 2023-03-27 15:19 UTC by mosquito

2023-03-28 02:12 UTC, Alviner approved these changes

2023-03-28 08:38 UTC, tzoiker commented on aio_pika/robust_channel.py
> +        if isinstance(exc, asyncio.CancelledError):
🤔

2023-03-28 11:31 UTC, Pavkazzz commented on aio_pika/channel.py
> +        warnings.warn("This property is deprecated, do not use this anymore.")
lets warn `DeprecationWarning`

2023-03-28 12:24 UTC, tzoiker submitted a review, later dismissed

2023-03-28 15:19 UTC, decaz requested changes

2023-03-28 15:19 UTC, decaz commented on aio_pika/robust_exchange.py
> +                "no need to pass this anymore.",
... **don't** need ...

2023-03-28 15:19 UTC, decaz commented on aio_pika/robust_queue.py
> +                "no need to pass this anymore.",
... **don't** need ...

2023-05-10 19:27 UTC, mosquito commented on aio_pika/robust_channel.py
>          await self._connection.ready()
`self._connection` might be in not initialised state when `self.ready` calling

2023-05-11 07:05 UTC, Alviner requested changes

2023-05-11 21:34 UTC, Alviner commented on aio_pika/patterns/master.py
> +            logging.error("Bad kwargs %r received for the %r", kwargs, func)
I mean that we don't use 'log' but 'logging' here

2023-05-19 14:09 UTC, Alviner submitted a review, later dismissed

2023-06-01 15:55 UTC, merged

2023-06-04 03:43 UTC, phillipuniverse commented
@mosquito question about this with the removed `connection` construct.

In the aio_pika OpenTelemetry instrumentation [located here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/a6797541721af72e6feab400e24ceaabc08cb31e/instrumentation/opentelemetry-instrumentation-aio-pika/src/opentelemetry/instrumentation/aio_pika/span_builder.py#L51-L64) there are a few fallbacks to getting the active URL from the channel. The connection url is being retrieved from the channel since that's all that is really available at publish time, which otel [decorates here](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/a6797541721af72e6feab400e24ceaabc08cb31e/instrumentation/opentelemetry-instrumentation-aio-pika/src/opentelemetry/instrumentation/aio_pika/publish_decorator.py#L41-L44).

I'm wondering if you have some advice on what the correct thing to do in this case would be to support the changes in 9.1 while still supporting 7.x, 8.x and 9.1+?

I would hate to drop down to use `channel._connection` (although that will work _most_ of the time), do you think change the method to async and use the `get_underlay_channel()`? Like this:

```python
     async def set_channel(self, channel: AbstractChannel):
        # aio_rmq 9.1 removed the connection attribute from the abstract listings
        if hasattr(channel, "get_underlay_channel"):
            connection = (await channel.get_underlay_channel()).connection
        else:
            connection = channel.connection
        if getattr(connection, "connection", None):
            # aio_rmq 7
            url = connection.connection.url
        else:
            # aio_rmq 8
            url = connection.url
        self._attributes.update(
            {
                SpanAttributes.NET_PEER_NAME: url.host,
                SpanAttributes.NET_PEER_PORT: url.port,
            }
        )
```

Or would it be better in your opinion to keep this sync and check for `channel._connection` like this:

```python
     async def set_channel(self, channel: AbstractChannel):
        # aio_rmq 9.1 removed the connection attribute from the abstract listings
        if hasattr(channel, "_connection"):
            connection = channel._connection
        else:
            connection = channel.connection
        if getattr(connection, "connection", None):
            # aio_rmq 7
            url = connection.connection.url
        else:
            # aio_rmq 8
            url = connection.url
        self._attributes.update(
            {
                SpanAttributes.NET_PEER_NAME: url.host,
                SpanAttributes.NET_PEER_PORT: url.port,
            }
        )
```