Fix reopen of robust channel after close
mosquito/aio-pika pull request #571
Opened 2023-08-05 15:36 UTC by decaz

Fixes #570.

2023-08-06 11:12 UTC, mosquito approved these changes

2023-08-06 11:14 UTC, Alviner approved these changes

2023-08-06 15:41 UTC, mosquito requested changes
So, we must wait channel will be declared before sending some channel-related frames.

2023-08-07 04:53 UTC, mosquito approved these changes
By bad. This should be ok

2023-08-07 04:54 UTC, merged