Fix bug with handling on_close with a RobustConnection
mosquito/aio-pika pull request #573
Opened 2023-08-12 03:23 UTC by CodeCorrupt

When handing on_close, futures were not properly popped from the futures list, causing an asyncio.exceptions.InvalidStateError when the connection is re-esablished and response recieved.

2023-08-12 04:41 UTC, CodeCorrupt commented
Alternatively, the futures could be popped by changing [this loop](https://github.com/mosquito/aio-pika/blob/c8e33c58ff7b81c6eeff58fcaf8c44ded82f9bce/aio_pika/patterns/rpc.py#L174-L178) to use `enumerate(self.futures)`, then pop using the `correlation_id`, and then just deleting the [`self.futures.pop(str(id(future)), None)`](https://github.com/mosquito/aio-pika/blob/c8e33c58ff7b81c6eeff58fcaf8c44ded82f9bce/aio_pika/patterns/rpc.py#L104C9-L104C48) line. But the PR I submitted seemed like a more general solution to me

2023-08-12 20:57 UTC, mosquito requested changes

2023-08-13 06:32 UTC, mosquito approved these changes

2023-08-13 09:23 UTC, decaz approved these changes

2023-08-13 20:12 UTC, mosquito commented
@CodeCorrupt I was thinking, the `on_close` is called quite rarely, maybe it makes sense to copy the whole sequence there so I don't have to do it every time here?

2023-08-14 14:05 UTC, merged

2023-08-14 14:08 UTC, mosquito commented
@CodeCorrupt released in 9.2.2