Define empty __slots__ in base classes
mosquito/aio-pika pull request #598
Opened 2023-11-13 21:54 UTC by anton-ryzhov

I've noticed that `__slots__` are defined in `Message`-classes, but they were not working as expected.

> When inheriting from a class without __slots__, the __dict__ and __weakref__ attribute of the instances will always be accessible.

https://docs.python.org/3/reference/datamodel.html?#object.__slots__

So all parent classes must also have `__slots__` to disable `__dict__` creation. That's what I did in this PR

2023-11-16 10:11 UTC, mosquito approved these changes

2023-11-20 09:14 UTC, decaz requested changes
@anton-ryzhov can you add `__slots__` for parent classes of `RobustQueue` which also has this attribute, please?

2023-11-20 21:40 UTC, anton-ryzhov commented
Done

2023-11-21 08:06 UTC, mosquito approved these changes

2023-11-21 13:03 UTC, decaz approved these changes

2023-11-21 13:28 UTC, merged